import type { Metadata } from "next";
import { Kanit as FontSans } from "next/font/google"
import "./globals.css";

import { cn } from "@/lib/utils";
import MainNav from "@/components/main-nav";
import MainFooter from "@/components/main-footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "400",
})

export const metadata: Metadata = {
  title: "Mankucha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased dark:bg-foreground",
          fontSans.variable)}>
        
        <MainNav />
        {children}
        <MainFooter />
        
      </body>
    </html>
  );
}
